######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 27 18:55:39 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DTW.h DTW_GUI.h Signal.h Test.h
FORMS += DTW_GUI.ui
SOURCES += DTW.cpp DTW_GUI.cpp main.cpp Signal.cpp Test.cpp
