######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 27 23:22:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DTW_GUI.h qcustomplot.h
FORMS += DTW_GUI.ui
SOURCES += DTW_GUI.cpp main.cpp qcustomplot.cpp
